@echo off
printf "==========================\nJupyter Notebook Converter\n==========================\n#                         #   #\n#           #       #     #   #                 #\n#           # #     #     #   #   #     # #     #\n#       #   # #     #     #   #   #     # #     #\n#       #   # #     #     #   # # #     # #     #\n#       #   # #     #     #   # # #     # #     #\n#       # # # # #   #     #   # # #     # # #   #\n#       # # # # #   # #   # # # # # #   # # # # #\n# # # # # # # # # # # # # # # # # # # # # # # # #\n\n\n"

echo Converting Notebook to html ...
jupyter nbconvert --execute --to html "car.ipynb"
echo Delete temporary files ...
rm -f index.html
echo Creating index.html ...
mv "car.html" "index.html" 
echo Finished, closing in 3 seconds ...
sleep 50
