# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: https://github.com/CodeChrisB/Kids-Project/tree/main/notebook
          output_dir: ../pdfs
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: notebook
          path: pdfs
